### ISSUE TITLE
Issues with splitting string fields

### ISSUE THREAD

**Issue by cristiansavaro** [awslabs/cloudwatch-logs-subscription-consumer#16]
@DVassallo : Am I correct to assume that if I add something like : 

```
    "eventSource": {
     "type": "string",
     "index": "not_analyzed"
    } 
```

to the [cwl_template.json](https://github.com/awslabs/cloudwatch-logs-subscription-consumer/blob/master/configuration/elasticsearch/templates/cwl_template.json) elasticsearch won't bother me with splitting the string fields as seen in the attached screen capture ?
![c2](https://cloud.githubusercontent.com/assets/10725599/14942131/7940a8b2-0fbc-11e6-8cc0-e3588b655f57.JPG)

**Comment by dvassallo** [comment]
Correct. It should go under mappings -> _default_ -> properties

**Comment by cristiansavaro** [comment]
thanks.
