### ISSUE TITLE
Support for multiple log groups

### ISSUE THREAD

**Issue by DorrinPk** [awslabs/cloudwatch-logs-subscription-consumer#18]
I have multiple log groups that I want to stream into this cloud formation stack. So far I've only been able to stream one of my log groups. Is there a way to support multiple log groups?

**Comment by DorrinPk** [comment]
Why can't a type be `CommaDelimitedList` ? instead of a `string` ?

**Comment by dvassallo** [comment]
Hello. At the moment this is not supported, but this is definitely a reasonable feature request. In the meantime, you should be able to workaround this by subscribing the other log groups manually with the [AWS CLI](https://aws.amazon.com/cli/):

```
aws logs put-subscription-filter \
    --log-group-name "<OTHER LOG GROUP NAME>" \
    --filter-name "CWL2ES" \
    --filter-pattern "" \
    --destination-arn "arn:aws:kinesis:<REGION>:<ACCOUNT_ID>:stream/<KINESIS_STREAM_NAME>" \
    --role-arn "arn:aws:iam::<ACCOUNT_ID>:role/<IAM_ROLE_NAME>"
```

Both the IAM role and the Kinesis stream would have been created for you automatically when setting up the first log group. You'd just have to find their names from the CloudFormation console.

**Comment by DorrinPk** [comment]
I used: 

```aws logs put-subscription-filter \
    --log-group-name "/aws/lambda/cc2_deploy_backlog" \
    --filter-name "CWL" \
    --filter-pattern "" \
    --destination-arn "arn:aws:kinesis:us-east-1:<account id>:stream/cloudwatchdashboard-KinesisSubscriptionStream-1C201WA49YM3Z" \
    --role-arn "arn:aws:iam::<account id>:role/CloudWatchLogsKinesisRole-AODD39XREG2P"
```

and it says : 

`An error occurred (InvalidParameterException) when calling the PutSubscriptionFilter operation: Could not deliver test message to specified Kinesis stream. Check if the given kinesis steam is in ACTIVE state.`

but it is in active state. 

`aws kinesis describe-stream --stream-name cloudwatchdashboard-KinesisSubscriptionStream-1C201WA49YM3Z` 

returns : `"StreamStatus": "ACTIVE"`

**Comment by javs-perez** [comment]
I would like to see this feature too! Do you have a timeline for it?

Thanks for your help.

**Comment by ghost** [comment]
Are there any updates on this request?

I could not get the subscription route to work

**Comment by sateesh-pagolu** [comment]
Is there any update on this feature?

**Comment by seancurran157** [comment]
any update on this feature?

**Comment by MahekPavagadhi** [comment]
Is there any update? @DVassallo
